# 通用配置依赖；仅通过 scripts/bootstrap.sh 显式安装。
brew "chezmoi"
brew "jq"
brew "ripgrep"
brew "fd"
brew "bat"
brew "eza"
brew "fzf"
brew "zoxide"
brew "starship"
brew "mise"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
